package lounges

// staticDataEurope is a regional shard of the curated lounge data.
// See static_data.go for the merge into staticData.
var staticDataEurope = map[string][]staticLounge{
	// ── Europe ──────────────────────────────────────────────────────────────
	"HEL": {
		// Priority Pass network lounges
		{
			Name:      "Aspire Lounge (Gate 13)",
			Terminal:  "Terminal 2, Schengen, Gate 13",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar", "Newspapers"},
			OpenHours: "05:00–09:00",
		},
		{
			Name:      "Aspire Lounge (Gate 27)",
			Terminal:  "Terminal 2, Schengen, Gate 27",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Newspapers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 2, Non-Schengen",
			Cards:     merge(ppDragon, amexPlatinum),
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–19:30",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "Finnair Premium Lounge (Schengen)",
			Terminal:  "Terminal 2, Gate 22",
			Cards:     []string{"Finnair Plus Gold", "Finnair Plus Platinum", "Oneworld Sapphire", "Oneworld Emerald", "Finnair Business Class"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Sauna"},
			OpenHours: "04:30–23:00",
		},
		{
			Name:      "Finnair Premium Lounge (Non-Schengen)",
			Terminal:  "Terminal 2, Gate 36",
			Cards:     []string{"Finnair Plus Gold", "Finnair Plus Platinum", "Oneworld Sapphire", "Oneworld Emerald", "Finnair Business Class"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–23:30",
		},
		// Bank-specific lounges
		{
			Name:      "OP Lounge",
			Terminal:  "Terminal 2, Schengen",
			Cards:     []string{"OP Visa Platinum", "OP Private Banking"},
			Amenities: []string{"Wi-Fi", "Snacks", "Coffee", "Newspapers", "Workstations"},
			OpenHours: "05:30–20:00",
		},
	},
	"LHR": {
		{
			Name:      "No1 Lounge",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers", "Spa treatments"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "No1 Lounge",
			Terminal:  "Terminal 5",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Club Aspire Lounge",
			Terminal:  "Terminal 5",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "04:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 4",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–22:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "British Airways Galleries First",
			Terminal:  "Terminal 5",
			Cards:     []string{"BA First Class", "Oneworld Emerald", "BA Gold"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "British Airways Galleries Club",
			Terminal:  "Terminal 5",
			Cards:     []string{"BA Business Class", "Oneworld Sapphire", "Oneworld Emerald", "BA Silver", "BA Gold"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers", "Workstations"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Virgin Atlantic Clubhouse",
			Terminal:  "Terminal 3",
			Cards:     []string{"Virgin Upper Class", "Virgin Gold"},
			Amenities: []string{"Wi-Fi", "Restaurant", "Cocktail bar", "Spa", "Pool table", "Showers"},
			OpenHours: "05:30–22:00",
		},
		// Amex Centurion Lounge
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 3",
			Cards:     amexCenturion,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–22:00",
		},
	},
	"CDG": {
		{
			Name:      "Salon des Lumières (Air France)",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "Salon Opéra (Air France)",
			Terminal:  "Terminal 2F",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–22:30",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 2E, Hall M",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "No1 Lounges CDG",
			Terminal:  "Terminal 2G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		// Air France airline lounges (NOT Priority Pass)
		{
			Name:      "Air France Business Lounge",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Air France Business Class", "SkyTeam Elite Plus", "Flying Blue Gold", "Flying Blue Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Champagne bar", "Showers", "Workstations"},
			OpenHours: "05:30–23:00",
		},
		{
			Name:      "Air France La Première Lounge",
			Terminal:  "Terminal 2E, Hall L",
			Cards:     []string{"Air France First Class", "Flying Blue Ultimate"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa", "Private suites"},
			OpenHours: "06:00–23:00",
		},
		// Amex Centurion Lounge (opened 2024)
		{
			Name:      "The Centurion Lounge",
			Terminal:  "Terminal 2E",
			Cards:     amexCenturion,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
	},
	"FRA": {
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 1, Pier B",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:30",
		},
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 1, Pier Z",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "05:30–21:30",
		},
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 2, Pier D",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:00",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 1, Pier A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		// Lufthansa airline lounges (status-only, NOT Priority Pass)
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 1, Concourse B",
			Cards:     []string{"Lufthansa First Class", "Lufthansa Business Class", "Star Alliance Gold", "Miles & More Senator", "Miles & More HON Circle"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Sleeping chairs", "Workstations"},
			OpenHours: "05:15–22:00",
		},
		{
			Name:      "Lufthansa Business Lounge (Pier A)",
			Terminal:  "Terminal 1, Pier A",
			Cards:     []string{"Lufthansa Business Class", "Star Alliance Gold", "Miles & More Senator", "Miles & More HON Circle", "Miles & More Frequent Traveller"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Workstations"},
			OpenHours: "05:15–22:00",
		},
		{
			Name:      "Lufthansa First Class Terminal",
			Terminal:  "Terminal 1, separate building",
			Cards:     []string{"Lufthansa First Class", "Miles & More HON Circle"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Cigar lounge", "Showers", "Bath", "Personal assistant", "Porsche transfer"},
			OpenHours: "05:00–22:00",
		},
	},
	"AMS": {
		{
			Name:      "Aspire Lounge (Schengen)",
			Terminal:  "Lounge 4, Pier F",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Aspire Lounge (Non-Schengen)",
			Terminal:  "Lounge 52, Pier G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "No1 Lounge Schiphol",
			Terminal:  "Main Terminal, Non-Schengen",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:30",
		},
	},
	"MUC": {
		{
			Name:      "Lufthansa Business Lounge",
			Terminal:  "Terminal 2, Level 04",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Lufthansa Senator Lounge",
			Terminal:  "Terminal 2, Level 04",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "05:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 1, Module D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:30",
		},
	},
	"ZRH": {
		{
			Name:      "SWISS Business Lounge",
			Terminal:  "Terminal E (Airside Center)",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "SWISS First Class Lounge",
			Terminal:  "Terminal E (Airside Center)",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa"},
			OpenHours: "06:00–21:30",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	"VIE": {
		{
			Name:      "Austrian Airlines Business Lounge",
			Terminal:  "Terminal F, Gate F04",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "Sky Lounge Vienna",
			Terminal:  "Terminal G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:00",
		},
	},
	"FCO": {
		{
			Name:      "Sala Partenze (Alitalia/ITA)",
			Terminal:  "Terminal 1",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:30–21:30",
		},
		{
			Name:      "Sala Laghi",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–22:00",
		},
		{
			Name:      "Sala Gioia",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
	"MXP": {
		{
			Name:      "Malpensa Premium Lounge",
			Terminal:  "Terminal 1, Landside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "04:30–22:30",
		},
		{
			Name:      "Sala Monteverdi",
			Terminal:  "Terminal 1, Airside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:30",
		},
	},
	"MAD": {
		{
			Name:      "Iberia VIP Lounge",
			Terminal:  "Terminal 4, Level 3",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
		{
			Name:      "Sala VIP Barcelona (Globalia)",
			Terminal:  "Terminal 4",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:30–21:00",
		},
		{
			Name:      "Aspire Lounge",
			Terminal:  "Terminal 4S",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–21:00",
		},
	},
	"BCN": {
		{
			Name:      "Sala VIP Barcelona",
			Terminal:  "Terminal 1, Level 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–22:00",
		},
		{
			Name:      "Sala Ágora",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "06:00–21:30",
		},
	},
	"CPH": {
		{
			Name:      "SAS Lounge Copenhagen",
			Terminal:  "Terminal 2, Gate C",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "No1 Lounge Copenhagen",
			Terminal:  "Terminal 2, Pier C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "05:30–21:00",
		},
	},
	"OSL": {
		{
			Name:      "SAS Lounge Oslo",
			Terminal:  "Main Terminal, Gate D",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "05:00–21:30",
		},
		{
			Name:      "No1 Lounge Oslo",
			Terminal:  "Main Terminal, Airside",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar"},
			OpenHours: "05:00–21:00",
		},
	},
}
