package lounges

// staticDataMideastAsia is a regional shard of the curated lounge data.
// See static_data.go for the merge into staticData.
var staticDataMideastAsia = map[string][]staticLounge{
	// ── Middle East ─────────────────────────────────────────────────────────
	"DXB": {
		{
			Name:      "G-Force Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Marhaba Lounge",
			Terminal:  "Terminal 3, Concourse B",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Prayer room"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Al Majlis Lounge (dnata)",
			Terminal:  "Terminal 3, Concourse C",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Ahlan Business Lounge",
			Terminal:  "Terminal 3, Concourse A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Showers", "Prayer room"},
			OpenHours: "24 hours",
		},
		// Emirates airline lounges (NOT Priority Pass)
		{
			Name:      "Emirates Business Class Lounge",
			Terminal:  "Terminal 3, Concourse B",
			Cards:     []string{"Emirates Business Class", "Emirates Skywards Gold", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa", "Barber"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Emirates First Class Lounge",
			Terminal:  "Terminal 3, Concourse A",
			Cards:     []string{"Emirates First Class", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Spa", "Cigar bar", "Shoe shine"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Emirates Business Class Lounge",
			Terminal:  "Terminal 3, Concourse C",
			Cards:     []string{"Emirates Business Class", "Emirates Skywards Gold", "Emirates Skywards Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
	},
	"DOH": {
		{
			Name:      "Qatar Airways Al Maha Arrivals Lounge",
			Terminal:  "Hamad International, Arrivals",
			Cards:     []string{"Priority Pass", "Diners Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Premium Terminal",
			Terminal:  "Hamad International",
			Cards:     []string{"Priority Pass"},
			Amenities: []string{"Wi-Fi", "A la carte dining", "Bar", "Showers", "Spa", "Sleeping suites"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Oryx Lounge",
			Terminal:  "Hamad International, Concourse D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Qatar Airways airline lounges (NOT Priority Pass)
		{
			Name:      "Qatar Airways Al Mourjan Business Lounge",
			Terminal:  "Hamad International, near Gate A2",
			Cards:     []string{"Qatar Airways Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Qatar Privilege Club Gold", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Restaurant", "Bar", "Showers", "Quiet rooms", "Family area", "Games room"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Al Mourjan Business Lounge — The Garden",
			Terminal:  "Hamad International, near Gate B",
			Cards:     []string{"Qatar Airways Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Qatar Privilege Club Gold", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Bar", "Showers", "Indoor garden", "Deli", "Quiet rooms"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Qatar Airways Al Safwa First Lounge",
			Terminal:  "Hamad International, near Gate A",
			Cards:     []string{"Qatar Airways First Class", "Oneworld Emerald", "Qatar Privilege Club Platinum"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Spa", "Showers", "Private suites", "Family lounge"},
			OpenHours: "24 hours",
		},
	},
	"IST": {
		{
			Name:      "Turkish Airlines Lounge (Domestic)",
			Terminal:  "Istanbul Airport, Domestic",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Turkish Airlines Lounge (International)",
			Terminal:  "Istanbul Airport, International",
			Cards:     []string{"Priority Pass", "Diners Club", "LoungeKey"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Library", "Golf simulator"},
			OpenHours: "24 hours",
		},
		{
			Name:      "IST Select Lounge",
			Terminal:  "Istanbul Airport, International",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
	},
	// ── Asia-Pacific ─────────────────────────────────────────────────────────
	"SIN": {
		{
			Name:      "Blossom Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping pods"},
			OpenHours: "24 hours",
		},
		{
			Name:      "SATS Premier Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "SATS Premier Lounge",
			Terminal:  "Terminal 3",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Plaza Premium Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "The Haven",
			Terminal:  "Terminal 1 (Jewel)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Napping pods"},
			OpenHours: "24 hours",
		},
		// Singapore Airlines airline lounges (NOT Priority Pass)
		{
			Name:      "Singapore Airlines SilverKris Business Class Lounge",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ Business Class", "Star Alliance Gold", "KrisFlyer Elite Gold", "KrisFlyer PPS Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Workstations"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Singapore Airlines SilverKris First Class Lounge",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ First Class", "Star Alliance Gold", "KrisFlyer PPS Club", "KrisFlyer Solitaire PPS"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Private rooms"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Singapore Airlines The Private Room",
			Terminal:  "Terminal 3",
			Cards:     []string{"SQ Suites Class", "SQ First Class", "KrisFlyer Solitaire PPS"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Private suites"},
			OpenHours: "24 hours",
		},
	},
	"NRT": {
		{
			Name:      "IASS Superior Lounge",
			Terminal:  "Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:30–21:30",
		},
		{
			Name:      "Sky Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "07:00–21:00",
		},
		{
			Name:      "Narita Airport IASS Executive Lounge No.2",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "07:00–22:00",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "ANA Lounge",
			Terminal:  "Terminal 1, Satellite 4F",
			Cards:     []string{"ANA Business Class", "Star Alliance Gold", "ANA Super Flyers Card", "ANA Diamond"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Noodle bar"},
			OpenHours: "07:00–21:30",
		},
		{
			Name:      "JAL Sakura Lounge",
			Terminal:  "Terminal 2, Main Building 3F",
			Cards:     []string{"JAL Business Class", "Oneworld Sapphire", "Oneworld Emerald", "JAL Global Club"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Massage chairs"},
			OpenHours: "07:30–21:30",
		},
		{
			Name:      "JAL First Class Lounge",
			Terminal:  "Terminal 2, Main Building 3F",
			Cards:     []string{"JAL First Class", "Oneworld Emerald", "JAL Diamond", "JAL JGC Premier"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Sushi bar", "Champagne bar", "Showers", "Massage"},
			OpenHours: "07:30–21:30",
		},
	},
	"HND": {
		{
			Name:      "Sky Lounge Annex",
			Terminal:  "Terminal 3 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "06:00–21:00",
		},
		{
			Name:      "TIAT Sky Lounge South",
			Terminal:  "Terminal 3 (International)",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "06:00–22:00",
		},
	},
	"ICN": {
		{
			Name:      "Matina Lounge",
			Terminal:  "Terminal 1, Concourse A",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Sky Hub Lounge",
			Terminal:  "Terminal 1, Concourse B",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Lotte Lounge",
			Terminal:  "Terminal 2",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Airline-specific lounges (NOT Priority Pass)
		{
			Name:      "Korean Air Prestige Class Lounge",
			Terminal:  "Terminal 2, Concourse",
			Cards:     []string{"Korean Air Business Class", "Korean Air First Class", "SkyTeam Elite Plus", "Korean Air Morning Calm Premium"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping area", "Workstations"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Korean Air First Class Lounge",
			Terminal:  "Terminal 2, Concourse",
			Cards:     []string{"Korean Air First Class", "Korean Air Morning Calm Premium", "SkyTeam Elite Plus"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Bar", "Showers", "Private suites", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Asiana Business Class Lounge",
			Terminal:  "Terminal 1, Concourse A",
			Cards:     []string{"Asiana Business Class", "Asiana First Class", "Star Alliance Gold", "Asiana Diamond Plus", "Asiana Diamond"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Napping area"},
			OpenHours: "24 hours",
		},
	},
	"HKG": {
		{
			Name:      "Plaza Premium Lounge (East Hall)",
			Terminal:  "Terminal 1, East Hall",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Plaza Premium Lounge (West Hall)",
			Terminal:  "Terminal 1, West Hall",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "BITA Lounge",
			Terminal:  "Terminal 1, Level 7",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		// Cathay Pacific airline lounges (NOT Priority Pass)
		{
			Name:      "Cathay Pacific The Pier Business Class Lounge",
			Terminal:  "Terminal 1, near Gate 65",
			Cards:     []string{"Cathay Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Cathay Marco Polo Gold", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Noodle bar", "Teahouse", "Bar", "Showers", "Day suites"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Pier First Class Lounge",
			Terminal:  "Terminal 1, near Gate 65",
			Cards:     []string{"Cathay First Class", "Oneworld Emerald", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Day suites", "Spa"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Wing Business Class Lounge",
			Terminal:  "Terminal 1, near Gate 1",
			Cards:     []string{"Cathay Business Class", "Oneworld Sapphire", "Oneworld Emerald", "Cathay Marco Polo Gold", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Noodle bar", "Bar", "Showers"},
			OpenHours: "05:30–00:30",
		},
		{
			Name:      "Cathay Pacific The Wing First Class Lounge",
			Terminal:  "Terminal 1, near Gate 1",
			Cards:     []string{"Cathay First Class", "Oneworld Emerald", "Cathay Marco Polo Diamond"},
			Amenities: []string{"Wi-Fi", "Fine dining", "Champagne bar", "Showers", "Cabanas"},
			OpenHours: "05:30–00:30",
		},
	},
	"BKK": {
		{
			Name:      "Miracle Lounge (Concourse D)",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Miracle Lounge (Concourse G)",
			Terminal:  "Suvarnabhumi, Concourse G",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Thai Airways Royal Orchid Lounge",
			Terminal:  "Suvarnabhumi, Level 4",
			Cards:     ppLK,
			Amenities: []string{"Wi-Fi", "Buffet", "Bar", "Showers"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Coral Executive Lounge",
			Terminal:  "Don Mueang, Terminal 1",
			Cards:     ppDragon,
			Amenities: []string{"Wi-Fi", "Snacks", "Bar"},
			OpenHours: "05:00–23:00",
		},
		// Thai Airways airline lounges (NOT Priority Pass)
		{
			Name:      "Thai Airways Royal Silk Lounge",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     []string{"Thai Business Class", "Star Alliance Gold", "Royal Orchid Plus Gold", "Royal Orchid Plus Platinum"},
			Amenities: []string{"Wi-Fi", "Hot food", "Bar", "Showers", "Spa", "Napping area"},
			OpenHours: "24 hours",
		},
		{
			Name:      "Thai Airways Royal First Lounge",
			Terminal:  "Suvarnabhumi, Concourse D",
			Cards:     []string{"Thai First Class", "Star Alliance Gold", "Royal Orchid Plus Platinum"},
			Amenities: []string{"Wi-Fi", "À la carte dining", "Champagne bar", "Showers", "Spa", "Private suites"},
			OpenHours: "24 hours",
		},
	},
}
